/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package proyecto_cafeteria.interfaz;

/**
 *
 * @author Cristel
 */
public class Inventario extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Inventario.class.getName());

    /**
     * Creates new form Inventario
     */
    public Inventario() {
        initComponents();
        setLocationRelativeTo(null);
        
        lbcafé.setText(ProyectoCafeteria1.productos[0].getNombre());
        lbstock1.setText("" + ProyectoCafeteria1.productos[0].getStock());
        lbReposteria.setText(ProyectoCafeteria1.productos[1].getNombre());
        lbstock2.setText("" + ProyectoCafeteria1.productos[1].getStock());
        lbRefrescos.setText(ProyectoCafeteria1.productos[2].getNombre());
        lbstock3.setText("" + ProyectoCafeteria1.productos[2].getStock());
        lbRetail.setText(ProyectoCafeteria1.productos[3].getNombre());
        lbstock4.setText("" + ProyectoCafeteria1.productos[3].getStock());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbInventario = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        lbPRODUCTOS = new javax.swing.JLabel();
        lbSTOCK = new javax.swing.JLabel();
        Salida = new javax.swing.JButton();
        lbcafé = new javax.swing.JLabel();
        lbReposteria = new javax.swing.JLabel();
        lbRefrescos = new javax.swing.JLabel();
        lbRetail = new javax.swing.JLabel();
        lbstock1 = new javax.swing.JLabel();
        lbstock2 = new javax.swing.JLabel();
        lbstock3 = new javax.swing.JLabel();
        lbstock4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Inventario_ POS_Starbucks");
        setBackground(new java.awt.Color(245, 241, 232));
        setPreferredSize(new java.awt.Dimension(900, 600));

        lbInventario.setFont(new java.awt.Font("Segoe UI Black", 0, 24)); // NOI18N
        lbInventario.setForeground(new java.awt.Color(3, 102, 53));
        lbInventario.setText("INVENTARIO");
        lbInventario.setToolTipText("");

        lbPRODUCTOS.setFont(new java.awt.Font("Monospaced", 1, 24)); // NOI18N
        lbPRODUCTOS.setForeground(new java.awt.Color(69, 47, 9));
        lbPRODUCTOS.setText("PRODUCTOS");

        lbSTOCK.setFont(new java.awt.Font("Monospaced", 1, 24)); // NOI18N
        lbSTOCK.setForeground(new java.awt.Color(69, 47, 9));
        lbSTOCK.setText("STOCK");

        Salida.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Salida.setForeground(new java.awt.Color(3, 102, 53));
        Salida.setText("Cerrar");
        Salida.addActionListener(this::SalidaActionPerformed);

        lbcafé.setFont(new java.awt.Font("Galgony", 0, 20)); // NOI18N
        lbcafé.setText("Café");

        lbReposteria.setFont(new java.awt.Font("Galgony", 0, 20)); // NOI18N
        lbReposteria.setText("Repostería");

        lbRefrescos.setFont(new java.awt.Font("Galgony", 0, 20)); // NOI18N
        lbRefrescos.setText("Refrescos");

        lbRetail.setFont(new java.awt.Font("Galgony", 0, 20)); // NOI18N
        lbRetail.setText("Retail");

        lbstock1.setFont(new java.awt.Font("Galgony", 0, 20)); // NOI18N
        lbstock1.setText("0");

        lbstock2.setFont(new java.awt.Font("Galgony", 0, 20)); // NOI18N
        lbstock2.setText("0");

        lbstock3.setFont(new java.awt.Font("Galgony", 0, 20)); // NOI18N
        lbstock3.setText("0");

        lbstock4.setFont(new java.awt.Font("Galgony", 0, 20)); // NOI18N
        lbstock4.setText("0");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(198, 198, 198)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbRetail)
                            .addComponent(lbRefrescos)
                            .addComponent(lbReposteria)
                            .addComponent(lbcafé))
                        .addGap(323, 323, 323)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lbstock4)
                            .addComponent(lbstock3)
                            .addComponent(lbstock2, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lbstock1, javax.swing.GroupLayout.Alignment.TRAILING)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(366, 366, 366)
                        .addComponent(lbInventario))
                    .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 1297, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 1748, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(168, 168, 168)
                        .addComponent(lbPRODUCTOS, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(288, 288, 288)
                        .addComponent(lbSTOCK, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(387, 387, 387)
                .addComponent(Salida, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(lbInventario)
                .addGap(18, 18, 18)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbPRODUCTOS)
                    .addComponent(lbSTOCK))
                .addGap(11, 11, 11)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbcafé)
                    .addComponent(lbstock1))
                .addGap(56, 56, 56)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbReposteria)
                    .addComponent(lbstock2))
                .addGap(57, 57, 57)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbRefrescos)
                    .addComponent(lbstock3))
                .addGap(60, 60, 60)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbRetail)
                    .addComponent(lbstock4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 95, Short.MAX_VALUE)
                .addComponent(Salida, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SalidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SalidaActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_SalidaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Inventario().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Salida;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel lbInventario;
    private javax.swing.JLabel lbPRODUCTOS;
    private javax.swing.JLabel lbRefrescos;
    private javax.swing.JLabel lbReposteria;
    private javax.swing.JLabel lbRetail;
    private javax.swing.JLabel lbSTOCK;
    private javax.swing.JLabel lbcafé;
    private javax.swing.JLabel lbstock1;
    private javax.swing.JLabel lbstock2;
    private javax.swing.JLabel lbstock3;
    private javax.swing.JLabel lbstock4;
    // End of variables declaration//GEN-END:variables
}
