/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package proyecto_cafeteria.interfaz;

import proyecto_cafeteria.modelos.Usuario;

/**
 *
 * @author Ei7Gr
 */
public class MenuAccess extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(MenuAccess.class.getName());

    /**
     * Creates new form MenuAccess
     */
    public MenuAccess() {
        initComponents();       
        setExtendedState(javax.swing.JFrame.MAXIMIZED_BOTH);
       

        Usuario usuarioLogin = Usuario.getInstance();
        lblBienvenido.setText(" Bienvenido : " + usuarioLogin.getNombreUsuario());
        
// Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    // This method is called from within the constructor to initialize the form.
    // * WARNING: Do NOT modify this code. The content of this method is always
    // * regenerated by the Form Editor.
    // */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        pnlLateral = new javax.swing.JPanel();
        lblNameStarbucks = new javax.swing.JLabel();
        btnComprar = new javax.swing.JButton();
        btnFacturar = new javax.swing.JButton();
        btnInventario = new javax.swing.JButton();
        btnCierreCaja = new javax.swing.JButton();
        lblBienvenido = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("POS STARBUCKS");
        setBackground(new java.awt.Color(84, 57, 54));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setPreferredSize(new java.awt.Dimension(1290, 1080));

        pnlLateral.setBackground(new java.awt.Color(3, 102, 53));
        pnlLateral.setPreferredSize(new java.awt.Dimension(600, 500));

        lblNameStarbucks.setFont(new java.awt.Font("Franklin Gothic Heavy", 0, 54)); // NOI18N
        lblNameStarbucks.setForeground(new java.awt.Color(255, 255, 255));
        lblNameStarbucks.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblNameStarbucks.setText("STARBUCKS");

        btnComprar.setFont(new java.awt.Font("Monospaced", 0, 24)); // NOI18N
        btnComprar.setText("Comprar");
        btnComprar.addActionListener(this::btnComprarActionPerformed);

        btnFacturar.setFont(new java.awt.Font("Monospaced", 0, 24)); // NOI18N
        btnFacturar.setText("Facturar");
        btnFacturar.addActionListener(this::btnFacturarActionPerformed);

        btnInventario.setFont(new java.awt.Font("Monospaced", 0, 24)); // NOI18N
        btnInventario.setText("Inventario");
        btnInventario.addActionListener(this::btnInventarioActionPerformed);

        btnCierreCaja.setFont(new java.awt.Font("Monospaced", 0, 24)); // NOI18N
        btnCierreCaja.setText("Cierre de Caja");
        btnCierreCaja.addActionListener(this::btnCierreCajaActionPerformed);

        lblBienvenido.setFont(new java.awt.Font("Perpetua", 1, 18)); // NOI18N
        lblBienvenido.setForeground(new java.awt.Color(255, 255, 255));
        lblBienvenido.setText("Bienvenido");

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyecto_cafeteria/recursos/iconStb.png"))); // NOI18N

        jButton1.setFont(new java.awt.Font("Monospaced", 0, 18)); // NOI18N
        jButton1.setText("Salir");
        jButton1.addActionListener(this::jButton1ActionPerformed);

        javax.swing.GroupLayout pnlLateralLayout = new javax.swing.GroupLayout(pnlLateral);
        pnlLateral.setLayout(pnlLateralLayout);
        pnlLateralLayout.setHorizontalGroup(
            pnlLateralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlLateralLayout.createSequentialGroup()
                .addGroup(pnlLateralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlLateralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(pnlLateralLayout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(lblBienvenido, javax.swing.GroupLayout.PREFERRED_SIZE, 295, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pnlLateralLayout.createSequentialGroup()
                            .addGap(148, 148, 148)
                            .addGroup(pnlLateralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(btnCierreCaja, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnInventario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnFacturar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lblNameStarbucks)
                                .addComponent(btnComprar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(pnlLateralLayout.createSequentialGroup()
                        .addGap(169, 169, 169)
                        .addComponent(jLabel1)))
                .addContainerGap(151, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlLateralLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(243, 243, 243))
        );
        pnlLateralLayout.setVerticalGroup(
            pnlLateralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlLateralLayout.createSequentialGroup()
                .addGap(93, 93, 93)
                .addComponent(lblNameStarbucks)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblBienvenido, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 137, Short.MAX_VALUE)
                .addComponent(btnComprar)
                .addGap(51, 51, 51)
                .addComponent(btnFacturar)
                .addGap(41, 41, 41)
                .addComponent(btnInventario)
                .addGap(43, 43, 43)
                .addComponent(btnCierreCaja)
                .addGap(39, 39, 39)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(156, 156, 156))
        );

        lblBienvenido.getAccessibleContext().setAccessibleName("lblBienvenido");

        getContentPane().add(pnlLateral, java.awt.BorderLayout.LINE_START);

        getAccessibleContext().setAccessibleDescription("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCierreCajaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCierreCajaActionPerformed
        CierreCaja pantalla = new CierreCaja();
        pantalla.setVisible(true);
    }//GEN-LAST:event_btnCierreCajaActionPerformed

    private void btnInventarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInventarioActionPerformed
        Inventario pantalla = new Inventario();
        pantalla.setVisible(true);
    }//GEN-LAST:event_btnInventarioActionPerformed

    private void btnFacturarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFacturarActionPerformed
        Factura pantalla = new Factura();
        pantalla.setVisible(true);
    }//GEN-LAST:event_btnFacturarActionPerformed

    private void btnComprarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnComprarActionPerformed
        CompraRegistro pantalla = new CompraRegistro();
        pantalla.setVisible(true);
    }//GEN-LAST:event_btnComprarActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new MenuAccess().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCierreCaja;
    private javax.swing.JButton btnComprar;
    private javax.swing.JButton btnFacturar;
    private javax.swing.JButton btnInventario;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblBienvenido;
    private javax.swing.JLabel lblNameStarbucks;
    private javax.swing.JPanel pnlLateral;
    // End of variables declaration//GEN-END:variables
}
